"""Chinese labels for generated SDD Delivery dashboard surfaces."""
from __future__ import annotations

TEXT = {
    "dashboard_title": "SDD Delivery 交付看板",
    "generated": "生成时间",
    "current_status": "当前状态",
    "goal": "目标",
    "next_action": "下一步",
    "current_phase": "当前阶段",
    "active_task": "当前任务",
    "delivery_metrics": "交付指标",
    "tasks_completed": "已完成任务",
    "checks_passed": "通过检查",
    "review_findings_closed": "已关闭审查项",
    "milestones": "里程碑",
    "gate_status": "门禁状态",
    "gate": "门禁",
    "status": "状态",
    "quality_status": "质量状态",
    "area": "范围",
    "mcp_evidence": "MCP 证据",
    "capability": "能力开关",
    "discovery": "发现状态",
    "items": "发现项",
    "source": "来源",
    "discovered_items": "发现对象",
    "risks": "风险",
    "blockers": "阻塞项",
    "human_reviews": "人工审查",
    "time": "时间",
    "reviewer": "审查人",
    "target": "对象",
    "result": "结果",
    "notes": "备注",
    "recent_events": "最近事件",
    "event": "事件",
    "detail": "详情",
    "evidence_files": "证据文件",
    "footer": "本看板是生成视图，事实源仍是当前目录中的 Markdown / JSON 产物。",
    "no_reviews": "暂无人工审查记录。",
    "no_events": "暂无事件记录。",
    "no_risks": "暂无风险记录。",
    "no_blockers": "暂无阻塞项记录。",
}

QUALITY_LABELS = {
    "progress": "进度",
    "traceability": "可追踪性",
    "test_evidence": "测试证据",
    "review_readiness": "审查就绪度",
    "delivery_confidence": "交付信心",
}
